server:
  port: 20120
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmall
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/org/augustus/user/mapper/*.xml
logging:
  level:
    org.augustus.user.mapper: debug
dubbo:
  application:
    name: gmall-user-service
  registry:
    protocol: zookeeper
    address: 192.168.0.110:2182,192.168.0.110:2181,192.168.0.110:2183
  protocol:
    name: dubbo
    port: 21120
  consumer:
    check: false