package org.augustus.bean;

import java.io.Serializable;
import java.util.List;

/**
 * Database Table Remarks:
 *   属性表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_base_attr_info
 */
public class PmsBaseAttrInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   属性名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_info.attr_name
     *
     * @mbg.generated
     */
    private String attrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_info.catalog3_id
     *
     * @mbg.generated
     */
    private Long catalog3Id;

    /**
     * Database Column Remarks:
     *   启用：1 停用：0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_info.is_enabled
     *
     * @mbg.generated
     */
    private String isEnabled;

    private List<PmsBaseAttrValue> attrValueList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_info.id
     *
     * @return the value of pms_base_attr_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_info.id
     *
     * @param id the value for pms_base_attr_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_info.attr_name
     *
     * @return the value of pms_base_attr_info.attr_name
     *
     * @mbg.generated
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_info.attr_name
     *
     * @param attrName the value for pms_base_attr_info.attr_name
     *
     * @mbg.generated
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_info.catalog3_id
     *
     * @return the value of pms_base_attr_info.catalog3_id
     *
     * @mbg.generated
     */
    public Long getCatalog3Id() {
        return catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_info.catalog3_id
     *
     * @param catalog3Id the value for pms_base_attr_info.catalog3_id
     *
     * @mbg.generated
     */
    public void setCatalog3Id(Long catalog3Id) {
        this.catalog3Id = catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_info.is_enabled
     *
     * @return the value of pms_base_attr_info.is_enabled
     *
     * @mbg.generated
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_info.is_enabled
     *
     * @param isEnabled the value for pms_base_attr_info.is_enabled
     *
     * @mbg.generated
     */
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled == null ? null : isEnabled.trim();
    }

    public List<PmsBaseAttrValue> getAttrValueList() {
        return attrValueList;
    }

    public void setAttrValueList(List<PmsBaseAttrValue> attrValueList) {
        this.attrValueList = attrValueList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", attrName=").append(attrName);
        sb.append(", catalog3Id=").append(catalog3Id);
        sb.append(", isEnabled=").append(isEnabled);
        sb.append(", attrValueList=").append(attrValueList);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}