package org.augustus.bean;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_base_catalog2
 */
public class PmsBaseCatalog2 implements Serializable {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_catalog2.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   二级分类名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_catalog2.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   一级分类编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_catalog2.catalog1_id
     *
     * @mbg.generated
     */
    private Integer catalog1Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_catalog2.id
     *
     * @return the value of pms_base_catalog2.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_catalog2.id
     *
     * @param id the value for pms_base_catalog2.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_catalog2.name
     *
     * @return the value of pms_base_catalog2.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_catalog2.name
     *
     * @param name the value for pms_base_catalog2.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_catalog2.catalog1_id
     *
     * @return the value of pms_base_catalog2.catalog1_id
     *
     * @mbg.generated
     */
    public Integer getCatalog1Id() {
        return catalog1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_catalog2.catalog1_id
     *
     * @param catalog1Id the value for pms_base_catalog2.catalog1_id
     *
     * @mbg.generated
     */
    public void setCatalog1Id(Integer catalog1Id) {
        this.catalog1Id = catalog1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", catalog1Id=").append(catalog1Id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}