package org.augustus.bean;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_base_catalog3
 */
public class PmsBaseCatalog3 implements Serializable {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_catalog3.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   三级分类名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_catalog3.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   二级分类编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_catalog3.catalog2_id
     *
     * @mbg.generated
     */
    private Long catalog2Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_base_catalog3
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_catalog3.id
     *
     * @return the value of pms_base_catalog3.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_catalog3.id
     *
     * @param id the value for pms_base_catalog3.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_catalog3.name
     *
     * @return the value of pms_base_catalog3.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_catalog3.name
     *
     * @param name the value for pms_base_catalog3.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_catalog3.catalog2_id
     *
     * @return the value of pms_base_catalog3.catalog2_id
     *
     * @mbg.generated
     */
    public Long getCatalog2Id() {
        return catalog2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_catalog3.catalog2_id
     *
     * @param catalog2Id the value for pms_base_catalog3.catalog2_id
     *
     * @mbg.generated
     */
    public void setCatalog2Id(Long catalog2Id) {
        this.catalog2Id = catalog2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", catalog2Id=").append(catalog2Id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}