package org.augustus.bean;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   库存单元图片表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_sku_image
 */
public class PmsSkuImage implements Serializable {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_image.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_image.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     * Database Column Remarks:
     *   图片名称（冗余）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_image.img_name
     *
     * @mbg.generated
     */
    private String imgName;

    /**
     * Database Column Remarks:
     *   图片路径(冗余)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_image.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     * Database Column Remarks:
     *   商品图片id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_image.product_img_id
     *
     * @mbg.generated
     */
    private Long spuImgId;

    /**
     * Database Column Remarks:
     *   是否默认
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_image.is_default
     *
     * @mbg.generated
     */
    private String isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_image.id
     *
     * @return the value of pms_sku_image.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_image.id
     *
     * @param id the value for pms_sku_image.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_image.sku_id
     *
     * @return the value of pms_sku_image.sku_id
     *
     * @mbg.generated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_image.sku_id
     *
     * @param skuId the value for pms_sku_image.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_image.img_name
     *
     * @return the value of pms_sku_image.img_name
     *
     * @mbg.generated
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_image.img_name
     *
     * @param imgName the value for pms_sku_image.img_name
     *
     * @mbg.generated
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_image.img_url
     *
     * @return the value of pms_sku_image.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_image.img_url
     *
     * @param imgUrl the value for pms_sku_image.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_image.product_img_id
     *
     * @return the value of pms_sku_image.product_img_id
     *
     * @mbg.generated
     */
    public Long getSpuImgId() {
        return spuImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_image.product_img_id
     *
     * @param spuImgId the value for pms_sku_image.product_img_id
     *
     * @mbg.generated
     */
    public void setSpuImgId(Long spuImgId) {
        this.spuImgId = spuImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_image.is_default
     *
     * @return the value of pms_sku_image.is_default
     *
     * @mbg.generated
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_image.is_default
     *
     * @param isDefault the value for pms_sku_image.is_default
     *
     * @mbg.generated
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault == null ? null : isDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", skuId=").append(skuId);
        sb.append(", imgName=").append(imgName);
        sb.append(", imgUrl=").append(imgUrl);
        sb.append(", spuImgId=").append(spuImgId);
        sb.append(", isDefault=").append(isDefault);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}