package org.augustus.bean;

import java.io.Serializable;
import java.util.List;

/**
 * Database Table Remarks:
 *   库存单元表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_sku_info
 */
public class PmsSkuInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   库存id(itemID)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.spuId
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     * Database Column Remarks:
     *   价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     * Database Column Remarks:
     *   sku名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.sku_name
     *
     * @mbg.generated
     */
    private String skuName;

    /**
     * Database Column Remarks:
     *   商品规格描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.sku_desc
     *
     * @mbg.generated
     */
    private String skuDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.weight
     *
     * @mbg.generated
     */
    private Double weight;

    /**
     * Database Column Remarks:
     *   品牌(冗余)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.tm_id
     *
     * @mbg.generated
     */
    private Long tmId;

    /**
     * Database Column Remarks:
     *   三级分类id（冗余)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.catalog3_id
     *
     * @mbg.generated
     */
    private Long catalog3Id;

    /**
     * Database Column Remarks:
     *   默认显示图片(冗余)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.sku_default_img
     *
     * @mbg.generated
     */
    private String skuDefaultImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    private List<PmsSkuSaleAttrValue> skuSaleAttrValueList;

    private List<PmsSkuAttrValue> skuAttrValueList;

    private List<PmsSkuImage> skuImageList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.id
     *
     * @return the value of pms_sku_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.id
     *
     * @param id the value for pms_sku_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.spuId
     *
     * @return the value of pms_sku_info.spuId
     *
     * @mbg.generated
     */
    public Long getSpuid() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.spuId
     *
     * @param spuId the value for pms_sku_info.spuId
     *
     * @mbg.generated
     */
    public void setSpuid(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.price
     *
     * @return the value of pms_sku_info.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.price
     *
     * @param price the value for pms_sku_info.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.sku_name
     *
     * @return the value of pms_sku_info.sku_name
     *
     * @mbg.generated
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.sku_name
     *
     * @param skuName the value for pms_sku_info.sku_name
     *
     * @mbg.generated
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.sku_desc
     *
     * @return the value of pms_sku_info.sku_desc
     *
     * @mbg.generated
     */
    public String getSkuDesc() {
        return skuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.sku_desc
     *
     * @param skuDesc the value for pms_sku_info.sku_desc
     *
     * @mbg.generated
     */
    public void setSkuDesc(String skuDesc) {
        this.skuDesc = skuDesc == null ? null : skuDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.weight
     *
     * @return the value of pms_sku_info.weight
     *
     * @mbg.generated
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.weight
     *
     * @param weight the value for pms_sku_info.weight
     *
     * @mbg.generated
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.tm_id
     *
     * @return the value of pms_sku_info.tm_id
     *
     * @mbg.generated
     */
    public Long getTmId() {
        return tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.tm_id
     *
     * @param tmId the value for pms_sku_info.tm_id
     *
     * @mbg.generated
     */
    public void setTmId(Long tmId) {
        this.tmId = tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.catalog3_id
     *
     * @return the value of pms_sku_info.catalog3_id
     *
     * @mbg.generated
     */
    public Long getCatalog3Id() {
        return catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.catalog3_id
     *
     * @param catalog3Id the value for pms_sku_info.catalog3_id
     *
     * @mbg.generated
     */
    public void setCatalog3Id(Long catalog3Id) {
        this.catalog3Id = catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.sku_default_img
     *
     * @return the value of pms_sku_info.sku_default_img
     *
     * @mbg.generated
     */
    public String getSkuDefaultImg() {
        return skuDefaultImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.sku_default_img
     *
     * @param skuDefaultImg the value for pms_sku_info.sku_default_img
     *
     * @mbg.generated
     */
    public void setSkuDefaultImg(String skuDefaultImg) {
        this.skuDefaultImg = skuDefaultImg == null ? null : skuDefaultImg.trim();
    }

    public List<PmsSkuSaleAttrValue> getSkuSaleAttrValueList() {
        return skuSaleAttrValueList;
    }

    public void setSkuSaleAttrValueList(List<PmsSkuSaleAttrValue> skuSaleAttrValueList) {
        this.skuSaleAttrValueList = skuSaleAttrValueList;
    }

    public List<PmsSkuAttrValue> getSkuAttrValueList() {
        return skuAttrValueList;
    }

    public void setSkuAttrValueList(List<PmsSkuAttrValue> skuAttrValueList) {
        this.skuAttrValueList = skuAttrValueList;
    }

    public List<PmsSkuImage> getSkuImageList() {
        return skuImageList;
    }

    public void setSkuImageList(List<PmsSkuImage> skuImageList) {
        this.skuImageList = skuImageList;
    }

    public Long getSpuId() {
        return spuId;
    }

    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", spuId=").append(spuId);
        sb.append(", price=").append(price);
        sb.append(", skuName=").append(skuName);
        sb.append(", skuDesc=").append(skuDesc);
        sb.append(", weight=").append(weight);
        sb.append(", tmId=").append(tmId);
        sb.append(", catalog3Id=").append(catalog3Id);
        sb.append(", skuDefaultImg=").append(skuDefaultImg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}