server:
  port: 20310
dubbo:
  application:
    name: gmall-item-web
  registry:
    protocol: zookeeper
    address: 192.168.0.110:2182,192.168.0.110:2181,192.168.0.110:2183
  consumer:
    check: false
spring:
  thymeleaf:
    cache: false
