package com.augustus.user.mapper;

import com.augustus.user.bean.UmsMemberReceiveAddress;

import java.util.List;

public interface UmsMemberReceiveAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_receive_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_receive_address
     *
     * @mbg.generated
     */
    int insert(UmsMemberReceiveAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_receive_address
     *
     * @mbg.generated
     */
    int insertSelective(UmsMemberReceiveAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_receive_address
     *
     * @mbg.generated
     */
    UmsMemberReceiveAddress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_receive_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UmsMemberReceiveAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_receive_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UmsMemberReceiveAddress record);

    /**
     * 根据 memberId查询收货地址
     * @param id
     * @return
     */
    List<UmsMemberReceiveAddress> findReceiveAddressByMemberId(Long id);
}