package org.augustus.manage.mapper;

import org.augustus.bean.PmsBaseAttrValue;

public interface PmsBaseAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbg.generated
     */
    int insert(PmsBaseAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbg.generated
     */
    int insertSelective(PmsBaseAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbg.generated
     */
    PmsBaseAttrValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmsBaseAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmsBaseAttrValue record);
}