package org.augustus.manage.mapper;

import org.augustus.bean.PmsBaseCatalog2;

import java.util.List;

public interface PmsBaseCatalog2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    int insert(PmsBaseCatalog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    int insertSelective(PmsBaseCatalog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    PmsBaseCatalog2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmsBaseCatalog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmsBaseCatalog2 record);

    List<PmsBaseCatalog2> findCatalog2ById(Integer id);
}