package org.augustus.manage.mapper;

import org.augustus.bean.PmsBaseCatalog3;

import java.util.List;

public interface PmsBaseCatalog3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbg.generated
     */
    int insert(PmsBaseCatalog3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbg.generated
     */
    int insertSelective(PmsBaseCatalog3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbg.generated
     */
    PmsBaseCatalog3 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmsBaseCatalog3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog3
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmsBaseCatalog3 record);

    List<PmsBaseCatalog3> findCatalog3ById(Integer id);
}