package org.augustus.manage.mapper;

import org.augustus.bean.PmsBaseAttrInfo;

import java.util.List;

public interface PmsBaseAttrInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    int insert(PmsBaseAttrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    int insertSelective(PmsBaseAttrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    PmsBaseAttrInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmsBaseAttrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmsBaseAttrInfo record);

    List<PmsBaseAttrInfo> findAttrInfoById(Integer catalog3Id);
}