package org.augustus.manage.mapper;

import org.augustus.bean.PmsProductInfo;

import java.util.List;

public interface PmsProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    int insert(PmsProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    int insertSelective(PmsProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    PmsProductInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmsProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmsProductInfo record);

    List<PmsProductInfo> getSpuList(Long catalog3Id);
}