package org.augustus.manage.mapper;

import org.augustus.bean.PmsProductImage;

import java.util.List;

public interface PmsProductImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_image
     *
     * @mbg.generated
     */
    int insert(PmsProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_image
     *
     * @mbg.generated
     */
    int insertSelective(PmsProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_image
     *
     * @mbg.generated
     */
    PmsProductImage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmsProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmsProductImage record);

    List<PmsProductImage> getSpuImageList(Long spuId);
}