package org.augustus.manage.mapper;

import org.apache.ibatis.annotations.Select;
import org.augustus.bean.PmsSkuImage;

import java.util.List;

public interface PmsSkuImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    int insert(PmsSkuImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    int insertSelective(PmsSkuImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    PmsSkuImage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmsSkuImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmsSkuImage record);

    List<PmsSkuImage> selectImageBySkuId(long skuId);
}