package org.augustus.manage.mapper;

import org.apache.ibatis.annotations.Select;
import org.augustus.bean.PmsSkuInfo;

public interface PmsSkuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    int insert(PmsSkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    int insertSelective(PmsSkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    PmsSkuInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmsSkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmsSkuInfo record);

    @Select("select spuId from gmall.pms_sku_info where id = #{skuId}")
    Long getSpuIdBySkuId(long skuId);
}