server:
  port: 20220
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmall
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.0.110
    port: 6379
mybatis:
  mapper-locations: classpath:/org/augustus/manage/mapper/*.xml
logging:
  level:
    org.augustus.manage.mapper: debug
dubbo:
  application:
    name: gmall-manage-service
  registry:
    protocol: zookeeper
    address: 192.168.0.110:2182,192.168.0.110:2181,192.168.0.110:2183
  protocol:
    name: dubbo
    port: 21220
  consumer:
    check: false